name: PeacefulMode
version: '1.0'
main: cn.peacefulMode.Main
api-version: '1.21'
softdepend:
  - PlaceholderAPI
commands:
  peacefulmode:
    description: Main command.
    aliases:
      - peace
      - pm
    usage: /<command>
permissions:
  peacefulmode.reload:
    default: op
  peacefulmode.toggle:
    default: op
  peacefulmode.toggle.other:
    default: op