name: PeacefulMode
version: '1.0'
main: cn.peacefulMode.Main
api-version: '1.21'
depend:
  - Vault
commands:
  peacefulmode:
    description: Main command.
    aliases:
      - nt
    usage: /<command>
permissions:
  peacefulmode.reload:
    description: Allow the player to reload the plugin.
    default: op
  peacefulmode.toggle:
    description: Allow the player to use the plugin.
    default: op